#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Regenerates docs/manifest-reference.md from schemas/sigil-schema.json.

.DESCRIPTION
    Walks every property in the JSON schema and emits a per-section table with
    type, required-flag, default, and description. The schema is the single
    source of truth — edit it (and run a schema-test to enforce that every
    property has a `description`), never the generated Markdown.

.NOTES
    Run from repo root.
#>

[CmdletBinding()]
param(
    [string] $SchemaPath = 'schemas/sigil-schema.json',
    [string] $OutPath    = 'docs/manifest-reference.md'
)

$ErrorActionPreference = 'Stop'
Set-Location (Split-Path $PSScriptRoot -Parent | Split-Path -Parent)

# -Depth was added in PowerShell 6.2; PS 5.1 has no override but defaults to 1024.
$convertArgs = @{}
if ($PSVersionTable.PSVersion.Major -ge 6) { $convertArgs['Depth'] = 100 }
# -Encoding UTF8 is required on Windows PowerShell 5.1: Get-Content -Raw with no
# -Encoding falls back to the system ANSI codepage, which mis-decodes the schema's
# UTF-8 em-dashes etc. into mojibake (e.g. "-" becomes "a<80><94>"). pwsh 7+ defaults
# to UTF-8 already, so this is a no-op there.
$schema = Get-Content $SchemaPath -Raw -Encoding UTF8 | ConvertFrom-Json @convertArgs

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<!-- Auto-generated by scripts/docs/generate-manifest-reference.ps1. Do not edit. -->')
[void]$sb.AppendLine('# `sigil.yaml` Manifest Reference')
[void]$sb.AppendLine()
[void]$sb.AppendLine("Source: ``$SchemaPath`` (JSON Schema, draft-07).")
[void]$sb.AppendLine()

function Render-PropertyTable {
    param($Properties, $Required, [string] $Heading)
    if (-not $Properties) { return }
    [void]$sb.AppendLine("## $Heading")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| Property | Type | Required | Default | Description |')
    [void]$sb.AppendLine('|---|---|---|---|---|')
    foreach ($name in $Properties.PSObject.Properties.Name) {
        $p = $Properties.$name
        $type = if ($p.type) { (@($p.type) -join ' / ') } elseif ($p.'$ref') { $p.'$ref' -replace '#/definitions/', '' } elseif ($p.enum) { 'enum: ' + ($p.enum -join ', ') } else { '-' }
        $req = if ($Required -contains $name) { 'yes' } else { '-' }
        $def = if ($null -ne $p.default) { '`' + $p.default + '`' } else { '-' }
        $desc = if ($p.description) { $p.description -replace '\|', '\|' } else { '_(undocumented)_' }
        [void]$sb.AppendLine("| ``$name`` | $type | $req | $def | $desc |")
    }
    [void]$sb.AppendLine()
}

# Top-level
Render-PropertyTable -Properties $schema.properties -Required $schema.required -Heading 'Top-level'

# Walk inline object properties one level deep so nested fields like
# installer.icon and parameters.<name>.screen show up in the reference. Without
# this recursion the table would only list `installer object` / `parameters
# object` with no breakdown of the actual sub-keys customers need.
function Get-NestedProperties {
    param($Property)
    if ($Property.properties) { return @{ Properties = $Property.properties; Required = $Property.required } }
    # parameters: { additionalProperties: { type: object, properties: { … } } }
    # — render the map-value shape so customers see what each parameter accepts.
    if ($Property.additionalProperties -and $Property.additionalProperties.properties) {
        return @{ Properties = $Property.additionalProperties.properties; Required = $Property.additionalProperties.required; IsMap = $true }
    }
    return $null
}

foreach ($name in $schema.properties.PSObject.Properties.Name) {
    $p = $schema.properties.$name
    $nested = Get-NestedProperties -Property $p
    if ($null -ne $nested) {
        $heading = if ($nested.IsMap) { "``$name.<name>``" } else { "``$name``" }
        Render-PropertyTable -Properties $nested.Properties -Required $nested.Required -Heading $heading
        # One more level: installer.brand has its own properties block.
        foreach ($childName in $nested.Properties.PSObject.Properties.Name) {
            $cp = $nested.Properties.$childName
            $childNested = Get-NestedProperties -Property $cp
            if ($null -ne $childNested) {
                $childHeading = if ($nested.IsMap) { "``$name.<name>.$childName``" } else { "``$name.$childName``" }
                Render-PropertyTable -Properties $childNested.Properties -Required $childNested.Required -Heading $childHeading
            }
        }
    }
}

# Each definition
if ($schema.definitions) {
    foreach ($defName in $schema.definitions.PSObject.Properties.Name) {
        $def = $schema.definitions.$defName
        if ($def.properties) {
            Render-PropertyTable -Properties $def.properties -Required $def.required -Heading "Definition: ``$defName``"
        }
        elseif ($def.description) {
            # Shape-only definitions (e.g. LocalizedText's `oneOf` a plain string
            # or an { en: ..., uk: ... } map) have no `properties` block to table
            # -- render the schema's own description prose instead so the shape
            # still appears here rather than silently dropping out.
            [void]$sb.AppendLine("## Definition: ``$defName``")
            [void]$sb.AppendLine()
            [void]$sb.AppendLine($def.description)
            [void]$sb.AppendLine()
        }
    }
}

# Always write UTF-8 without BOM so output is byte-identical across PS 5.1
# (which adds a BOM on -Encoding utf8) and pwsh 7+ (which doesn't).
[System.IO.File]::WriteAllText(
    [System.IO.Path]::GetFullPath($OutPath),
    $sb.ToString(),
    [System.Text.UTF8Encoding]::new($false))
Write-Host "wrote $OutPath"
