#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Regenerates docs/cli-reference.md from the live `sigil` CLI command tree.

.DESCRIPTION
    Walks every subcommand declared by the System.CommandLine tree in
    src/SigilBuild.Cli/ by invoking `dotnet run -- <command> --help` recursively,
    parses the output, and renders a Markdown reference at docs/cli-reference.md.

    Source of truth: the `Description` / `HelpText` attributes on each Command
    and Option in src/SigilBuild.Cli/. Edit those — never edit the generated
    Markdown by hand.

.NOTES
    Run from repo root. Requires net10.0 SDK on PATH.
#>

[CmdletBinding()]
param(
    [string] $CliProject = 'src/SigilBuild.Cli/SigilBuild.Cli.csproj',
    [string] $OutPath    = 'docs/cli-reference.md'
)

$ErrorActionPreference = 'Stop'
Set-Location (Split-Path $PSScriptRoot -Parent | Split-Path -Parent)

# Subcommand list: ground truth is the `sigil --help` output.
$rootHelp = & dotnet run --project $CliProject --no-build -- --help 2>&1
if ($LASTEXITCODE -ne 0) { throw "sigil --help exited $LASTEXITCODE" }

# Naive parse: lines under "Commands:" until the first blank line.
$lines = $rootHelp -split "`n"
$inCommands = $false
$subcommands = @()
foreach ($line in $lines) {
    if ($line -match '^Commands:') { $inCommands = $true; continue }
    if ($inCommands) {
        if ($line -match '^\s+([a-z][a-z0-9-]*)\s+(.*)$') {
            $subcommands += [pscustomobject]@{ Name = $Matches[1]; Description = $Matches[2].Trim() }
        }
        elseif ($line -match '^\s*$') { break }
    }
}

# Emit the reference.
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<!-- Auto-generated by scripts/docs/generate-cli-reference.ps1. Do not edit. -->')
[void]$sb.AppendLine('# `sigil` CLI Reference')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Command | Description |')
[void]$sb.AppendLine('|---|---|')
foreach ($cmd in $subcommands) {
    [void]$sb.AppendLine("| [`sigil $($cmd.Name)`](#sigil-$($cmd.Name)) | $($cmd.Description) |")
}
[void]$sb.AppendLine()

foreach ($cmd in $subcommands) {
    [void]$sb.AppendLine("## `sigil $($cmd.Name)`")
    [void]$sb.AppendLine()
    $cmdHelp = & dotnet run --project $CliProject --no-build -- $cmd.Name --help 2>&1
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine(($cmdHelp | Out-String).TrimEnd())
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine()
}

Set-Content -Path $OutPath -Value $sb.ToString() -Encoding utf8 -NoNewline
Write-Host "wrote $OutPath ($($subcommands.Count) subcommands)"
