#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Regenerates docs/manifest-reference.md from schemas/sigil-schema.json.

.DESCRIPTION
    Walks every property in the JSON schema and emits a per-section table with
    type, required-flag, default, and description. The schema is the single
    source of truth — edit it (and run a schema-test to enforce that every
    property has a `description`), never the generated Markdown.

.NOTES
    Run from repo root.
#>

[CmdletBinding()]
param(
    [string] $SchemaPath = 'schemas/sigil-schema.json',
    [string] $OutPath    = 'docs/manifest-reference.md'
)

$ErrorActionPreference = 'Stop'
Set-Location (Split-Path $PSScriptRoot -Parent | Split-Path -Parent)

# -Depth was added in PowerShell 6.2; PS 5.1 has no override but defaults to 1024.
$convertArgs = @{}
if ($PSVersionTable.PSVersion.Major -ge 6) { $convertArgs['Depth'] = 100 }
$schema = Get-Content $SchemaPath -Raw | ConvertFrom-Json @convertArgs

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<!-- Auto-generated by scripts/docs/generate-manifest-reference.ps1. Do not edit. -->')
[void]$sb.AppendLine('# `sigil.yaml` Manifest Reference')
[void]$sb.AppendLine()
[void]$sb.AppendLine("Source: ``$SchemaPath`` (JSON Schema, draft-07).")
[void]$sb.AppendLine()

function Render-PropertyTable {
    param($Properties, $Required, [string] $Heading)
    if (-not $Properties) { return }
    [void]$sb.AppendLine("## $Heading")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| Property | Type | Required | Default | Description |')
    [void]$sb.AppendLine('|---|---|---|---|---|')
    foreach ($name in $Properties.PSObject.Properties.Name) {
        $p = $Properties.$name
        $type = if ($p.type) { (@($p.type) -join ' / ') } elseif ($p.'$ref') { $p.'$ref' -replace '#/definitions/', '' } elseif ($p.enum) { 'enum: ' + ($p.enum -join ', ') } else { '-' }
        $req = if ($Required -contains $name) { 'yes' } else { '-' }
        $def = if ($null -ne $p.default) { '`' + $p.default + '`' } else { '-' }
        $desc = if ($p.description) { $p.description -replace '\|', '\|' } else { '_(undocumented)_' }
        [void]$sb.AppendLine("| ``$name`` | $type | $req | $def | $desc |")
    }
    [void]$sb.AppendLine()
}

# Top-level
Render-PropertyTable -Properties $schema.properties -Required $schema.required -Heading 'Top-level'

# Each definition
if ($schema.definitions) {
    foreach ($defName in $schema.definitions.PSObject.Properties.Name) {
        $def = $schema.definitions.$defName
        if ($def.properties) {
            Render-PropertyTable -Properties $def.properties -Required $def.required -Heading "Definition: ``$defName``"
        }
    }
}

Set-Content -Path $OutPath -Value $sb.ToString() -Encoding utf8 -NoNewline
Write-Host "wrote $OutPath"
