using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace SigilBuild.Localization.Generator;

internal static class StringsEmitter
{
    public static string Emit(IReadOnlyList<CatalogFile> files)
    {
        var en = files.FirstOrDefault(f => f.Lang == "en");
        if (en is null)
        {
            return "// no Strings.en.txt found\n";
        }

        var langs = files.Select(f => f.Lang).Where(l => l != "en").OrderBy(l => l, StringComparer.Ordinal).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Generated by SigilBuild.Localization.Generator. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace SigilBuild.Wrapper.Core.Localization;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Chrome languages Sigil ships. Closed set; see ADR-008 §4.</summary>");
        sb.Append("public enum Lang { En");
        foreach (var l in langs)
        {
            sb.Append(", ").Append(Pascal(l));
        }
        sb.AppendLine(", Pseudo }");
        sb.AppendLine();
        sb.AppendLine("public static class Strings");
        sb.AppendLine("{");

        foreach (var entry in en.Entries)
        {
            var method = MethodName(entry.Key);
            var args = entry.Placeholders;
            var paramList = args.Count == 0
                ? "Lang lang"
                : "Lang lang, " + string.Join(", ", args.Select(a => "string " + a));

            sb.AppendLine($"    public static string {method}({paramList}) => lang switch");
            sb.AppendLine("    {");

            foreach (var file in files.Where(f => f.Lang != "en").OrderBy(f => f.Lang, StringComparer.Ordinal))
            {
                var translated = file.Entries.FirstOrDefault(e => e.Key == entry.Key);
                if (translated is null)
                {
                    continue; // SIGLOC002 warns; falls through to the English default.
                }
                sb.AppendLine($"        Lang.{Pascal(file.Lang)} => {Expression(translated.Value)},");
            }

            sb.AppendLine($"        Lang.Pseudo => {Expression(PseudoTransform.Apply(entry.Value))},");
            sb.AppendLine($"        _ => {Expression(entry.Value)},");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // The tag map, emitted from the catalog files themselves. LanguageResolver
        // consumes this instead of hardcoding a list, so adding Strings.de.txt wires
        // the language end-to-end with no code edit — which is what ADR-008 §4's
        // "languages ship as content contributions" rule actually requires.
        sb.AppendLine("/// <summary>Chrome language tags, emitted from the catalog files. Never hand-edit.</summary>");
        sb.AppendLine("public static class ChromeCatalog");
        sb.AppendLine("{");
        sb.Append("    public static readonly string[] Tags = { \"en\"");
        foreach (var l in langs)
        {
            sb.Append(", \"").Append(l).Append('"');
        }
        sb.AppendLine(" };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps a catalog tag to its Lang. Unknown tags fall back to English.</summary>");
        sb.AppendLine("    public static Lang FromTag(string tag) => tag switch");
        sb.AppendLine("    {");
        foreach (var l in langs)
        {
            sb.AppendLine($"        \"{l}\" => Lang.{Pascal(l)},");
        }
        sb.AppendLine("        _ => Lang.En,");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();

        // `S` — session-resolved static accessors for XAML {x:Static}. Only argless
        // keys get one: a key with placeholders needs an argument, so it must go
        // through a ViewModel property instead (design §7.1).
        sb.AppendLine("/// <summary>Session-resolved chrome strings for XAML <c>{x:Static}</c>.</summary>");
        sb.AppendLine("public static class S");
        sb.AppendLine("{");
        foreach (var entry in en.Entries.Where(e => e.Placeholders.Count == 0))
        {
            var method = MethodName(entry.Key);
            sb.AppendLine($"    public static string {method} => Strings.{method}(SessionLanguage.Current);");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Turns "Upgrading {appName} to {v}." into: "Upgrading " + appName + " to " + v + "."
    /// Concatenation, never string.Format — no CultureInfo is involved at any point.
    /// </summary>
    private static string Expression(string value)
    {
        var parts = new List<string>();
        var literal = new StringBuilder();

        for (var i = 0; i < value.Length; i++)
        {
            if (value[i] == '{')
            {
                var close = value.IndexOf('}', i);
                if (close > i)
                {
                    var name = value.Substring(i + 1, close - i - 1);
                    if (CatalogParser.IsPlaceholderName(name))
                    {
                        if (literal.Length > 0)
                        {
                            parts.Add(Quote(literal.ToString()));
                            literal.Clear();
                        }
                        parts.Add(name);
                        i = close;
                        continue;
                    }
                }
            }
            literal.Append(value[i]);
        }

        if (literal.Length > 0)
        {
            parts.Add(Quote(literal.ToString()));
        }

        return parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
    }

    private static string Quote(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";

    private static string MethodName(string key) =>
        string.Concat(key.Split('.', '_').Select(Pascal));

    private static string Pascal(string s)
    {
        if (s.Length == 0) return s;
        var cleaned = s.Replace("-", string.Empty);
        if (cleaned.Length == 0) return string.Empty;
        return char.ToUpper(cleaned[0], CultureInfo.InvariantCulture) + cleaned.Substring(1);
    }
}
